-- =====================================================================
-- Migration 0088 : Cover every foreign key with an index
--
-- 90 foreign keys had no covering index. Postgres does not create one
-- automatically for the REFERENCING side, so each of these made two things
-- slow: any join or filter on the column, and — more sharply — every DELETE
-- or UPDATE of the referenced parent row, which must scan the whole child
-- table to enforce the constraint.
--
-- This is the `unindexed_foreign_keys` finding from the Supabase performance
-- advisor. Index names follow idx_<table>_<column>; `if not exists` makes the
-- whole file safely repeatable.
--
-- Generated by walking pg_constraint for single-column FKs with no index
-- whose first key matches the constrained column.
-- =====================================================================

create index if not exists idx_app_users_lab_id on app_users(lab_id);
create index if not exists idx_appointments_device_id on appointments(device_id);
create index if not exists idx_appointments_lab_id on appointments(lab_id);
create index if not exists idx_asset_movement_items_source_lab_id on asset_movement_items(source_lab_id);
create index if not exists idx_asset_movement_items_source_warehouse_id on asset_movement_items(source_warehouse_id);
create index if not exists idx_asset_movement_items_target_lab_id on asset_movement_items(target_lab_id);
create index if not exists idx_asset_movement_items_target_warehouse_id on asset_movement_items(target_warehouse_id);
create index if not exists idx_bank_accounts_party_company_id on bank_accounts(party_company_id);
create index if not exists idx_bank_accounts_party_lab_id on bank_accounts(party_lab_id);
create index if not exists idx_bank_transaction_rules_party_company_id on bank_transaction_rules(party_company_id);
create index if not exists idx_bank_transaction_rules_party_lab_id on bank_transaction_rules(party_lab_id);
create index if not exists idx_bank_transactions_import_log_id on bank_transactions(import_log_id);
create index if not exists idx_bank_transactions_matched_rule_id on bank_transactions(matched_rule_id);
create index if not exists idx_bank_transactions_party_company_id on bank_transactions(party_company_id);
create index if not exists idx_bank_transactions_party_lab_id on bank_transactions(party_lab_id);
create index if not exists idx_blanket_order_items_product_id on blanket_order_items(product_id);
create index if not exists idx_blanket_orders_lab_id on blanket_orders(lab_id);
create index if not exists idx_blanket_orders_supplier_id on blanket_orders(supplier_id);
create index if not exists idx_bom_items_component_id on bom_items(component_id);
create index if not exists idx_bom_items_source_warehouse on bom_items(source_warehouse);
create index if not exists idx_contracts_device_id on contracts(device_id);
create index if not exists idx_contracts_service_product_id on contracts(service_product_id);
create index if not exists idx_delivery_note_items_kit_batch_id on delivery_note_items(kit_batch_id);
create index if not exists idx_delivery_notes_lab_id on delivery_notes(lab_id);
create index if not exists idx_delivery_trip_stops_delivery_note_id on delivery_trip_stops(delivery_note_id);
create index if not exists idx_delivery_trip_stops_lab_id on delivery_trip_stops(lab_id);
create index if not exists idx_devices_product_id on devices(product_id);
create index if not exists idx_devices_warehouse_id on devices(warehouse_id);
create index if not exists idx_installation_note_items_device_id on installation_note_items(device_id);
create index if not exists idx_item_prices_supplier_id on item_prices(supplier_id);
create index if not exists idx_journal_entry_accounts_party_company_id on journal_entry_accounts(party_company_id);
create index if not exists idx_journal_entry_accounts_party_lab_id on journal_entry_accounts(party_lab_id);
create index if not exists idx_kit_batches_supplier_id on kit_batches(supplier_id);
create index if not exists idx_kit_batches_warehouse_id on kit_batches(warehouse_id);
create index if not exists idx_leads_converted_lab_id on leads(converted_lab_id);
create index if not exists idx_maintenance_schedules_lab_id on maintenance_schedules(lab_id);
create index if not exists idx_maintenance_schedules_team_id on maintenance_schedules(team_id);
create index if not exists idx_maintenance_visit_purposes_device_id on maintenance_visit_purposes(device_id);
create index if not exists idx_material_request_items_product_id on material_request_items(product_id);
create index if not exists idx_material_request_items_warehouse_id on material_request_items(warehouse_id);
create index if not exists idx_material_requests_purchase_id on material_requests(purchase_id);
create index if not exists idx_opportunities_lab_id on opportunities(lab_id);
create index if not exists idx_opportunities_lead_id on opportunities(lead_id);
create index if not exists idx_payment_entries_party_company_id on payment_entries(party_company_id);
create index if not exists idx_payment_entries_party_lab_id on payment_entries(party_lab_id);
create index if not exists idx_payment_requests_lab_id on payment_requests(lab_id);
create index if not exists idx_payment_requests_mode_of_payment_id on payment_requests(mode_of_payment_id);
create index if not exists idx_pick_list_items_product_id on pick_list_items(product_id);
create index if not exists idx_pick_list_items_warehouse_id on pick_list_items(warehouse_id);
create index if not exists idx_pick_lists_lab_id on pick_lists(lab_id);
create index if not exists idx_pick_lists_sales_order_id on pick_lists(sales_order_id);
create index if not exists idx_product_bundle_items_component_id on product_bundle_items(component_id);
create index if not exists idx_purchase_invoices_payment_term_id on purchase_invoices(payment_term_id);
create index if not exists idx_purchase_items_product_id on purchase_items(product_id);
create index if not exists idx_purchase_items_warehouse_id on purchase_items(warehouse_id);
create index if not exists idx_purchase_order_items_product_id on purchase_order_items(product_id);
create index if not exists idx_purchase_orders_purchase_id on purchase_orders(purchase_id);
create index if not exists idx_purchase_receipt_items_product_id on purchase_receipt_items(product_id);
create index if not exists idx_purchase_receipt_items_warehouse_id on purchase_receipt_items(warehouse_id);
create index if not exists idx_purchase_receipts_purchase_order_id on purchase_receipts(purchase_order_id);
create index if not exists idx_purchase_receipts_supplier_id on purchase_receipts(supplier_id);
create index if not exists idx_quality_inspections_product_id on quality_inspections(product_id);
create index if not exists idx_quotation_items_product_id on quotation_items(product_id);
create index if not exists idx_quotations_lab_id on quotations(lab_id);
create index if not exists idx_quotations_opportunity_id on quotations(opportunity_id);
create index if not exists idx_quotations_sales_order_id on quotations(sales_order_id);
create index if not exists idx_rfq_items_product_id on rfq_items(product_id);
create index if not exists idx_rfq_suppliers_supplier_id on rfq_suppliers(supplier_id);
create index if not exists idx_rfq_suppliers_supplier_quotation_id on rfq_suppliers(supplier_quotation_id);
create index if not exists idx_sales_kit_batch_id on sales(kit_batch_id);
create index if not exists idx_sales_product_id on sales(product_id);
create index if not exists idx_sales_invoice_items_product_id on sales_invoice_items(product_id);
create index if not exists idx_sales_invoices_sales_order_id on sales_invoices(sales_order_id);
create index if not exists idx_sales_order_items_product_id on sales_order_items(product_id);
create index if not exists idx_sales_orders_lab_id on sales_orders(lab_id);
create index if not exists idx_sales_return_items_product_id on sales_return_items(product_id);
create index if not exists idx_serial_numbers_device_id on serial_numbers(device_id);
create index if not exists idx_serial_numbers_warehouse_id on serial_numbers(warehouse_id);
create index if not exists idx_stock_entries_from_warehouse on stock_entries(from_warehouse);
create index if not exists idx_stock_entries_to_warehouse on stock_entries(to_warehouse);
create index if not exists idx_stock_entry_items_batch_id on stock_entry_items(batch_id);
create index if not exists idx_stock_reconciliation_items_kit_batch_id on stock_reconciliation_items(kit_batch_id);
create index if not exists idx_supplier_quotation_items_product_id on supplier_quotation_items(product_id);
create index if not exists idx_supplier_quotations_purchase_id on supplier_quotations(purchase_id);
create index if not exists idx_supplier_quotations_supplier_id on supplier_quotations(supplier_id);
create index if not exists idx_warranty_claims_device_id on warranty_claims(device_id);
create index if not exists idx_warranty_claims_product_id on warranty_claims(product_id);
create index if not exists idx_work_orders_batch_id on work_orders(batch_id);
create index if not exists idx_work_orders_bom_id on work_orders(bom_id);
create index if not exists idx_work_orders_fg_warehouse on work_orders(fg_warehouse);
